Login
simpleflags/simpleflags pull request #1
Opened 2022-03-17 20:07 UTC by hamzabisevac

2022-03-17 20:09 UTC, enverbisevac commented on src/App.tsx
> +  const [count, setCount] = useState(0);
unused state? pls remove it

2022-03-17 20:10 UTC, enverbisevac commented on src/App.tsx
> +import "./App.css";
pls use best practice to sort imports

2022-03-17 20:10 UTC, enverbisevac commented on src/App.tsx
> +      style={{
you should use styled component for this

2022-03-17 20:11 UTC, enverbisevac commented on src/App.tsx
> +        <Route path="/Home" element={<Home />} />
you must follow best practice for defining urls:
forgot-password
signup
home -> /

2022-03-17 20:12 UTC, enverbisevac commented on src/components/ForgetPassword/index.tsx
> +      confirmPassword: "sevret",
password should not contain default values

2022-03-23 15:13 UTC, farismecinovic commented on src/components/Flag/index.tsx
> +          </li> */}
remove comments pls

2022-03-24 19:43 UTC, darishodzic requested changes

2022-03-24 19:43 UTC, darishodzic commented on src/App.css
> +
pls remove comments

2022-03-24 19:43 UTC, darishodzic commented on src/App.tsx
> +    <AppLogo>
This should be something like AppWrapper

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +    console.log(gender);
pls remove clg

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +  const [gender, setGender] = React.useState();
what you think about 'useState'  instead of 'React.useState'

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +              background: activeFlags.includes("red-1")
please make theme and use them

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +                        console.log(activeFlags);
remove clg

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +                      console.log(activeFlags);
remove clg

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +              backgroundColor: activeFlags.includes("red-3")
use theme and pls dont use inline styles

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +                        console.log(activeFlags);
remove clg

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +                        console.log(activeFlags);
remove clg

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +              backgroundColor: activeFlags.includes("red-5")
use theme and pls dont use inline css

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +                      console.log(activeFlags);
remove clg

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +    border-bottom: 1px solid #0278d5;
use theme pls

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flag/index.tsx
> +    border-bottom: 1px solid #0278d5;
use theme pls

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flags/index.tsx
> +  border-bottom: 1px solid #d9dae5;
theme

2022-03-24 19:43 UTC, darishodzic commented on src/components/Flags/index.tsx
> +  background-color: #effbff;
theme

2022-03-24 19:43 UTC, darishodzic commented on src/components/ForgotPassword/index.tsx
> +      style={{
pls dont use inline css

2022-03-24 19:43 UTC, darishodzic commented on src/components/Login/index.tsx
> +      }}
pls dont use inline css

2022-03-24 19:43 UTC, darishodzic commented on src/components/Login/index.tsx
> +  box-shadow: 0px 2px 15px 5px #dedede;
theme

2022-03-24 19:43 UTC, darishodzic commented on src/components/Login/index.tsx
> +  color: #0278d5;
theme

2022-03-24 19:43 UTC, darishodzic commented on src/components/Login/index.tsx
> +const Password = styled.div``;
empty?

2022-03-24 19:43 UTC, darishodzic commented on src/components/Navigation/index.tsx
> +  const [color, setColor] = useState<any[]>([]);
type?

2022-03-24 19:43 UTC, darishodzic commented on src/components/Navigation/index.tsx
> +        }}
pls dont use inline css

2022-03-24 19:43 UTC, darishodzic commented on src/components/Navigation/index.tsx
> +        }}
inline css

2022-03-24 19:43 UTC, darishodzic commented on src/components/Navigation/index.tsx
> +      >
inline css

2022-03-24 19:43 UTC, darishodzic commented on src/components/SignUp/index.tsx
> +      }}
inline css

2022-03-24 19:43 UTC, darishodzic commented on src/logo.svg
> +</svg>
delete this pls

2022-07-12 17:58 UTC, merged